server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/msb_dongbao_test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    password: '0804'
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver